title: Optimizer Benchmark
description: A benchmarking framework for evaluating and comparing 97+ PyTorch optimization algorithms on 2D mathematical test functions. Features hyperparameter tuning with Optuna, trajectory visualizations, and performance rankings to help researchers and developers choose the right optimizer. optimizer benchmark
theme: jekyll-theme-cayman
